In [36]:
import pandas as pd
import numpy as np

In [37]:
df=pd.read_csv("milknew.csv")

In [38]:
df.head()

pH  Temprature  Taste  Odor  Fat   Turbidity  Colour   Grade
0  6.6          35      1     0     1          0     254    high
1  6.6          36      0     1     0          1     253    high
2  8.5          70      1     1     1          1     246     low
3  9.5          34      1     1     0          1     255     low
4  6.6          37      0     0     0          0     255  medium

In [39]:
df['Grade']=df['Grade'].map({"high":2,"low":0,"medium":1})

In [40]:
x=df.iloc[:,:-1]
x

pH  Temprature  Taste  Odor  Fat   Turbidity  Colour
0     6.6          35      1     0     1          0     254
1     6.6          36      0     1     0          1     253
2     8.5          70      1     1     1          1     246
3     9.5          34      1     1     0          1     255
4     6.6          37      0     0     0          0     255
...   ...         ...    ...   ...   ...        ...     ...
1054  6.7          45      1     1     0          0     247
1055  6.7          38      1     0     1          0     255
1056  3.0          40      1     1     1          1     255
1057  6.8          43      1     0     1          0     250
1058  8.6          55      0     1     1          1     255

[1059 rows x 7 columns]

In [41]:
y = df['Grade']
y

0       2
1       2
2       0
3       0
4       1
       ..
1054    1
1055    2
1056    0
1057    2
1058    0
Name: Grade, Length: 1059, dtype: int64

In [42]:
y

0       2
1       2
2       0
3       0
4       1
       ..
1054    1
1055    2
1056    0
1057    2
1058    0
Name: Grade, Length: 1059, dtype: int64

In [43]:
y.value_counts()

Grade
0    429
1    374
2    256
Name: count, dtype: int64

In [44]:
x

pH  Temprature  Taste  Odor  Fat   Turbidity  Colour
0     6.6          35      1     0     1          0     254
1     6.6          36      0     1     0          1     253
2     8.5          70      1     1     1          1     246
3     9.5          34      1     1     0          1     255
4     6.6          37      0     0     0          0     255
...   ...         ...    ...   ...   ...        ...     ...
1054  6.7          45      1     1     0          0     247
1055  6.7          38      1     0     1          0     255
1056  3.0          40      1     1     1          1     255
1057  6.8          43      1     0     1          0     250
1058  8.6          55      0     1     1          1     255

[1059 rows x 7 columns]

In [45]:
from sklearn.tree import DecisionTreeClassifier
model= DecisionTreeClassifier()

In [46]:
from sklearn.linear_model import LogisticRegression
model2 = LogisticRegression(max_iter=1000,solver="liblinear")

In [47]:
from sklearn.neighbors import KNeighborsClassifier
model3 = KNeighborsClassifier(n_neighbors=7)

In [48]:
from sklearn.model_selection import StratifiedKFold,cross_val_score
valid = StratifiedKFold(10)

In [49]:
result = cross_val_score(model,x,y,cv= valid)
result
result.mean()

np.float64(0.9933962264150944)

In [50]:
result2 = cross_val_score(model2,x,y,cv = valid)
result2
result2.mean()

np.float64(0.7384456424079066)

In [51]:
result3 = cross_val_score(model3,x,y,cv = valid)
result3
result3.mean()

np.float64(0.9914914645103325)

In [52]:
from sklearn.model_selection import train_test_split as tts
x_train,x_test,y_train,y_test = tts(x,y,train_size=0.8,random_state=0)

In [53]:
x_train.shape,y_train.shape

((847, 7), (847,))

In [54]:
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [55]:
y_train_pred = model.predict(x_train)
y_test_pred = model.predict(x_test)

In [57]:
from sklearn.metrics import confusion_matrix,accuracy_score
print("Training")
print("Accuracy : ",accuracy_score(y_train,y_train_pred)*100)
print(confusion_matrix(y_train,y_train_pred))

Training
Accuracy :  100.0
[[360   0   0]
 [  0 297   0]
 [  0   0 190]]


In [58]:
import pickle
pickle.dump(model,open('milk_model1.pkl','wb'))